import { Box, Container } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Engineer SNS Client</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box
        bgColor="teal.400"
        color="gray.100"
        fontWeight="bold"
        mb={4}
        padding={4}
      >
        <Container>Engineer SNS Client</Container>
      </Box>

      <Container>{children}</Container>

      <footer></footer>
    </div>
  )
}
