import { Box, Container, Icon, HStack } from '@chakra-ui/react'
import Head from 'next/head'
import React from 'react'
import { FaGithub } from 'react-icons/fa'

export default function Layout({ children }) {
  return (
    <div>
      <Head>
        <title>Engineer SNS Client</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Box
        bgColor="teal.400"
        color="gray.100"
        fontWeight="bold"
        mb={4}
        padding={4}
      >
        <Container>
          <Box display="flex" justifyContent="space-between">
            <Box>Engineer SNS Client</Box>
            <HStack spacing={4}>
              <a href="https://qiita.com/HawkClaws/items/599d7666f55e79ef7f56">
                Qiita
              </a>
              <a href="https://github.com/dala00/engineer-sns-client">
                <Icon as={FaGithub} w={6} h={6} />
              </a>
            </HStack>
          </Box>
        </Container>
      </Box>

      <Container>{children}</Container>

      <footer></footer>
    </div>
  )
}
